### ISSUE TITLE
Spawned shell keys not echoed

### ISSUE THREAD

**Issue by bkauler** [dylanaraps/shfm#12]
Running on desktop, Sakura terminal emulator, TERM=xterm, when hit "!" to spawn a shell, keys are not echoed to the screen. Works, but not echoed.

I found the culprit, it is this commit "use alternative screen to avoid redraws":

https://github.com/dylanaraps/shfm/commit/60119b02629abf127fb25ebf1498d5a9c2f7def5

The commit before that, in a shell can type and it is echoed.

Regards,
Barry

**Comment by dylanaraps** [comment]
Pushed a commit to possibly fix this. Mind sending the output of: `infocmp`?

**Comment by bkauler** [comment]
Yes, that fixes it, thanks.

**Comment by bkauler** [comment]
Yes, that fixes it, thanks.
