### ISSUE TITLE
Screen not cleared when spawn shell

### ISSUE THREAD

**Issue by bkauler** [dylanaraps/shfm#14]
No problem when running a terminal emulator in X, however, without X, or in the initramfs, when the "!" key pressed, the prompt appears at top of screen and the prior shfm output is still there. Ditto when type "exit" to go back to shfm, the shell output is still there.

With nnn, "!" causes the prompt to display at bottom of screen, everything is still there, just rolls up.
With nnn, typing "exit" rewrites the screen with the nnn output.

**Comment by dylanaraps** [comment]
Fixed, thanks. Was using the "alternate buffer" sequence to store the screen's contents when a shell or command was run. Swapped to actually calculating the previous state. The "alternate buffer" is now used to save the screen's contents **before** shfm is run. Great changes all around. Let me know if the issue still persists, I can no longer reproduce it on my end.
