### ISSUE TITLE
Directories with no hidden files display the hidden file matching pattern as a file

### ISSUE THREAD

**Issue by ghost** [dylanaraps/shfm#16]
Tested with bash and dash.

When a directory has no hidden files, toggling visibility of hidden files shows `.[!.]*` as the only file in the directory, and doing some tests in general show that when there is no matching pattern to it the shell just prints the pattern as is, like it does here.

**Comment by dylanaraps** [comment]
This was intentional. Regardless, I've fixed this. Will show `empty` if no items in directory, `no results` for a failed search and `no hidden files` if there aren't any. Thanks.
