### ISSUE TITLE
Problem with opener

### ISSUE THREAD

**Issue by huijunchen9260** [dylanaraps/shfm#17]
Dear Dylan:

When I made an opener to open pdf files in `shfm` in `zathura`, if I turn back to the `shfm` terminal window, and press keys, those keys will be executed. Is it possible to either disable keyboard input when open files in external program, or make `shfm` behave like `fff` and still usable after opening a file in external program?

**Comment by dylanaraps** [comment]
Hello. See this example opener script. Simply call the applications with `&` and `setsid` to detach them from the terminal.

```sh
#!/bin/sh -e
#
# open file in application based on file extension

case $1 in
    *.mp3|*.flac|*.wav|\
    *.mp4|*.mkv|*.webm|\
    *.png|*.gif|*.jpg|*.jpe|*.jpeg)
        setsid mpv --force-window "$1" >/dev/null 2>&1 &
    ;;

    *.html|*.pdf)
        setsid firefox "$1" >/dev/null 2>&1 &
    ;;

    # all other files
    *)
        "${EDITOR:=vim}" "$1"
    ;;
esac
```
