### ISSUE TITLE
Cannot enter directory when pressing `G`

### ISSUE THREAD

**Issue by huijunchen9260** [dylanaraps/shfm#18]
Dear Dylan:

If the first item in my `$PWD` is a file, and the final item is directory, if I press `G`, the highlight will go to the directory, but when I press `l`, it is actually opening that file (the first item).

The possible cause for this might because the `$cur` variable is not updated when I press `G`. Does it possible to solve this?

**Comment by dylanaraps** [comment]
This is fixed in master, forgot to close.
