### ISSUE TITLE
cannot pass the `shellcheck` test

### ISSUE THREAD

**Issue by ghost** [dylanaraps/shfm#2]
When I check `shfm` script with [shellcheck](https://github.com/koalaman/shellcheck), your code doesn't pass this test:

```bash
$ shellcheck ./shfm 

In ./shfm line 19:
    set +f -- $(stty size)
              ^----------^ SC2046: Quote this to prevent word splitting.

For more information:
  https://www.shellcheck.net/wiki/SC2046 -- Quote this to prevent word splitt...
```

Please fix this error to improve the quality of source code.

**Comment by dylanaraps** [comment]
Yes. This is not an error. It's a false positive. The behavior is intentional and globbing is disabled.

**Comment by dylanaraps** [comment]
Fixed and added CI: https://github.com/dylanaraps/shfm/commit/15789232c8209d52e9a9fddd440febcf357f2b4d

**Comment by dylanaraps** [comment]
This is mentioned in shellcheck's Wiki here if you're interested: https://github.com/koalaman/shellcheck/wiki/SC2046#exceptions
