### ISSUE TITLE
image previews

### ISSUE THREAD

**Issue by pfr-dev** [dylanaraps/shfm#24]
The only thing keeping me from switching from `fff` to `shfm` is image previews. Is this possible?

**Comment by YerinAlexey** [comment]
Image previews are bloat

**Comment by dther** [comment]
I have doubts that this can be accomplished with POSIX shell, but I think this can be implemented using tmux, a special tmux.conf and a wrapper script. I'll give it a shot and reply to this issue in case anyone is interested.

**Comment by pfr-dev** [comment]
I've noticed that `w3mimagedisplay` doesn't play very nice with `allacritty` anyway, so I've actually requested that `fff` use `ueberzug` for image previews instead. I wonder if it can be implemented in `shfm` ? I suppose it is a dependency that some people may not want but it can be optional i guess

**Comment by dylanaraps** [comment]
Outta scope.

**Comment by pfr-dev** [comment]
> I have doubts that this can be accomplished with POSIX shell, but I think this can be implemented using tmux, a special tmux.conf and a wrapper script. I'll give it a shot and reply to this issue in case anyone is interested.

Did you have any luck?

 

> Outta scope.

No worries. What about for `fff` though?
