### ISSUE TITLE
About strange screen rendering when open files in neovim

### ISSUE THREAD

**Issue by huijunchen9260** [dylanaraps/shfm#5]
Dear @dylanaraps:

As shown in the screenshot below, when I open any file in neovim, it seems that the screen rendering is not correct. There is a useless statusbar, and that statusbar will raise when you scroll down.

![image](https://user-images.githubusercontent.com/54217138/89314474-afe0f880-d647-11ea-993c-91767cf171d6.png)

EDIT: 
I also wish to know how to write my own TUI in just POSIX shell. The setting of this file manager is just way too facinating. I wish to rewrite my own bibliography manager [dmenubib](https://github.com/huijunchen9260/dmenubib) into this types of TUI application.

**Comment by dylanaraps** [comment]
Can you reproduce with the latest master?

**Comment by dylanaraps** [comment]
Fixed.

**Comment by huijunchen9260** [comment]
Thx!

Would you mind sharing with me how to build such TUI system?
